# Generated by Django 3.0.8 on 2020-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price2',
            field=models.FloatField(max_length=4),
        ),
    ]
