# Generated by Django 3.0.8 on 2020-08-21 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200821_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pricetwo',
        ),
        migrations.AddField(
            model_name='project',
            name='dimensions',
            field=models.CharField(default=' 10 x 18', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='projects.OrderItem'),
        ),
    ]
