# Generated by Django 3.0.8 on 2020-08-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200821_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
    ]
