# Generated by Django 3.0.8 on 2020-08-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.FloatField(default='100'),
            preserve_default=False,
        ),
    ]
