# Generated by Django 3.0.8 on 2020-08-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='35x10', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='dimensions',
            field=models.CharField(max_length=10),
        ),
    ]
