# Generated by Django 3.0.8 on 2020-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.AddField(
            model_name='project',
            name='postid',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
