# Generated by Django 3.0.8 on 2020-08-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200812_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='price',
            new_name='elevenbyfourprice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='sixteenbytwentyprice',
            field=models.FloatField(default=10.00),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='twentybytwentyfourprice',
            field=models.FloatField(default=10.00),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='twentyfourbythirtysixprice',
            field=models.FloatField(default=10.00),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='postid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
