# Generated by Django 3.0.8 on 2020-08-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200816_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='elevenbyfourprice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twentybytwentyfourprice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='twentyfourbythirtysixprice',
        ),
    ]
