# Generated by Django 3.0.8 on 2020-08-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200816_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sixteenbytwentyprice',
        ),
        migrations.AddField(
            model_name='project',
            name='elevenbyfourteenprice',
            field=models.FloatField(default=10, max_length=4),
            preserve_default=False,
        ),
    ]
